# Prequesite

In [103]:
! python -m venv .venv
! source .venv/bin/activate

In [104]:
! pip install --upgrade pip
! pip install ipykernel
! python -m ipykernel install --name=.venv
! pip install numpy pandas
! pip freeze > requirements.txt

Installed kernelspec .venv in /usr/local/share/jupyter/kernels/.venv


In [105]:
from pathlib import Path
from solutions.task1_domain import ReadJson, CSRInquiries, ShiftsDetail
from solutions import task1, task2, task3
import numpy as np
from functools import reduce

read_json = ReadJson(Path("data/json"))
shifts_dict = read_json.read_shifts()
day_dict = read_json.read_days()

In [106]:
shifts_detail = ShiftsDetail(shifts_dict)
csr_inquiries = CSRInquiries(day_dict)

In [107]:
coefficients_c = np.ones(shifts_detail.num_of_shifts)

In [108]:
stat = [
    (2 if day_j < 5 else 1) * task1.min_csr_of_a_day(coefficients_c, csr_inquiries, shifts_detail, day_j) 
    for day_j in range(csr_inquiries.num_of_days)
]
stat

[array([14,  0,  2,  4,  0,  4]),
 array([14,  0,  4,  2,  0,  6]),
 array([12,  0,  2,  4,  0,  6]),
 array([12,  0,  0,  6,  2,  6]),
 array([8, 0, 4, 2, 0, 6]),
 array([5, 0, 0, 3, 0, 4]),
 array([5, 0, 0, 3, 1, 2])]

In [109]:
min_total_csr = max([reduce(lambda pre, cur: pre + cur, days, 0) for days in stat])

In [110]:
employee_assignment = np.array(
    [task1.label_shift_to_employee(shift, shifts_detail.columns, min_total_csr) for shift in stat]
).T.tolist()

In [111]:
schedule = {f"NV{i}": em for i, em in enumerate(employee_assignment)}
schedule

{'NV0': ['C1', 'C1', 'C1', 'C1', 'C1', 'C1', 'C1'],
 'NV1': ['C1', 'C1', 'C1', 'C1', 'C1', 'C1', 'C1'],
 'NV2': ['C1', 'C1', 'C1', 'C1', 'C1', 'C1', 'C1'],
 'NV3': ['C1', 'C1', 'C1', 'C1', 'C1', 'C1', 'C1'],
 'NV4': ['C1', 'C1', 'C1', 'C1', 'C1', 'C1', 'C1'],
 'NV5': ['C1', 'C1', 'C1', 'C1', 'C1', 'C4', 'C4'],
 'NV6': ['C1', 'C1', 'C1', 'C1', 'C1', 'C4', 'C4'],
 'NV7': ['C1', 'C1', 'C1', 'C1', 'C1', 'C4', 'C4'],
 'NV8': ['C1', 'C1', 'C1', 'C1', 'C3', 'C6', 'C5'],
 'NV9': ['C1', 'C1', 'C1', 'C1', 'C3', 'C6', 'C6'],
 'NV10': ['C1', 'C1', 'C1', 'C1', 'C3', 'C6', 'C6'],
 'NV11': ['C1', 'C1', 'C1', 'C1', 'C3', 'C6', None],
 'NV12': ['C1', 'C1', 'C3', 'C4', 'C4', None, None],
 'NV13': ['C1', 'C1', 'C3', 'C4', 'C4', None, None],
 'NV14': ['C3', 'C3', 'C4', 'C4', 'C6', None, None],
 'NV15': ['C3', 'C3', 'C4', 'C4', 'C6', None, None],
 'NV16': ['C4', 'C3', 'C4', 'C4', 'C6', None, None],
 'NV17': ['C4', 'C3', 'C4', 'C4', 'C6', None, None],
 'NV18': ['C4', 'C4', 'C6', 'C5', 'C6', None, None],
 'N

In [112]:
# schedule = task2.solve(schedule)
# schedule

In [113]:
task3.solve(shifts_dict, day_dict, schedule)

        message: Optimization terminated successfully. (HiGHS Status 7: Optimal)
        success: True
         status: 0
            fun: 101.0
              x: [ 1.000e+00  0.000e+00 ...  0.000e+00  0.000e+00]
            nit: -1
          lower:  residual: [ 1.000e+00  0.000e+00 ...  0.000e+00
                              0.000e+00]
                 marginals: [ 0.000e+00  0.000e+00 ...  0.000e+00
                              0.000e+00]
          upper:  residual: [       inf        inf ...        inf
                                    inf]
                 marginals: [ 0.000e+00  0.000e+00 ...  0.000e+00
                              0.000e+00]
          eqlin:  residual: []
                 marginals: []
        ineqlin:  residual: [ 0.000e+00  1.000e+00 ...  0.000e+00
                              0.000e+00]
                 marginals: [ 0.000e+00  0.000e+00 ...  0.000e+00
                              0.000e+00]
 mip_node_count: 1
 mip_dual_bound: 101.0
        mip_gap: 0.0
[

{'NV0': ['C1', None, None, 'C3', 'C5', 'C1', 'C6'],
 'NV1': ['C1', None, None, None, 'C6', None, 'C1'],
 'NV2': [None, None, 'C6', None, 'C1', 'C1', None],
 'NV3': [None, 'C1', 'C6', None, None, 'C1', None],
 'NV4': ['C1', None, 'C5', None, 'C1', None, 'C6'],
 'NV5': ['C1', 'C5', None, None, 'C6', 'C4', 'C1'],
 'NV6': ['C6', 'C4', 'C1', None, None, 'C3', 'C1'],
 'NV7': [None, None, 'C5', 'C6', None, 'C1', 'C1'],
 'NV8': [None, 'C1', None, 'C6', 'C1', None, None],
 'NV9': ['C1', 'C6', None, None, None, 'C1', None],
 'NV10': ['C1', 'C1', None, None, None, None, 'C6'],
 'NV11': [None, None, None, 'C6', 'C1', None, 'C1'],
 'NV12': ['C1', 'C5', 'C6', None, None, None, 'C1'],
 'NV13': [None, 'C1', None, 'C1', None, 'C6', 'C5'],
 'NV14': [None, None, 'C1', 'C1', 'C4', None, 'C6'],
 'NV15': ['C1', 'C6', None, 'C4', 'C3', None, 'C1'],
 'NV16': ['C5', None, 'C1', 'C1', 'C6', 'C3', None],
 'NV17': ['C6', 'C1', None, 'C1', None, None, 'C5'],
 'NV18': ['C3', None, None, 'C1', 'C6', None, 'C1'],
 'N

Failed miserably :>>>

In [115]:
import math

table_1 = {
    name: [math.ceil(period / 2) if name != "Saturday" else period for period in shift]
    for name, shift in day_dict.items() if name != "Sunday"
}
table_1

{'Monday': [3, 5, 5, 4, 2, 2, 4, 4, 4, 3, 2, 2, 1],
 'Tuesday': [3, 5, 4, 4, 2, 2, 4, 3, 5, 3, 2, 2, 2],
 'Wednesday': [4, 5, 5, 3, 2, 2, 3, 4, 4, 2, 2, 2, 2],
 'Thursday': [3, 5, 4, 3, 2, 2, 3, 4, 4, 3, 2, 2, 2],
 'Friday': [3, 4, 4, 4, 2, 3, 3, 4, 3, 3, 2, 2, 2],
 'Saturday': [6, 9, 9, 4, 3, 3, 4, 5, 5, 5, 3, 3, 2]}

In [116]:
import math

table_2 = {
    name: [math.ceil(period / 2) if name != "Sunday" else period for period in shift]
    for name, shift in day_dict.items() if name != "Saturday"
}
table_2

{'Monday': [3, 5, 5, 4, 2, 2, 4, 4, 4, 3, 2, 2, 1],
 'Tuesday': [3, 5, 4, 4, 2, 2, 4, 3, 5, 3, 2, 2, 2],
 'Wednesday': [4, 5, 5, 3, 2, 2, 3, 4, 4, 2, 2, 2, 2],
 'Thursday': [3, 5, 4, 3, 2, 2, 3, 4, 4, 3, 2, 2, 2],
 'Friday': [3, 4, 4, 4, 2, 3, 3, 4, 3, 3, 2, 2, 2],
 'Sunday': [5, 7, 6, 5, 4, 3, 4, 5, 6, 5, 3, 3, 3]}

In [117]:
schedule_1 = task1.solve(shifts_dict, table_1)
schedule_1

{'NV0': ['C1', 'C1', 'C1', 'C1', 'C1', 'C1'],
 'NV1': ['C1', 'C1', 'C1', 'C1', 'C1', 'C1'],
 'NV2': ['C1', 'C1', 'C1', 'C1', 'C3', 'C1'],
 'NV3': ['C1', 'C6', 'C3', 'C3', 'C4', 'C1'],
 'NV4': ['C4', None, 'C4', 'C4', 'C6', 'C1'],
 'NV5': ['C4', None, 'C6', 'C6', 'C6', 'C4'],
 'NV6': ['C6', None, 'C6', 'C6', None, 'C4'],
 'NV7': [None, None, None, None, None, 'C4'],
 'NV8': [None, None, None, None, None, 'C6'],
 'NV9': [None, None, None, None, None, 'C6'],
 'NV10': [None, None, None, None, None, 'C6'],
 'NV11': [None, None, None, None, None, 'C6']}

In [118]:
schedule_2 = task1.solve(shifts_dict, table_2)
schedule_2

{'NV0': ['C1', 'C1', 'C1', 'C1', 'C1', 'C1'],
 'NV1': ['C1', 'C1', 'C1', 'C1', 'C1', 'C1'],
 'NV2': ['C1', 'C1', 'C1', 'C1', 'C3', 'C1'],
 'NV3': ['C1', 'C6', 'C3', 'C3', 'C4', 'C1'],
 'NV4': ['C4', None, 'C4', 'C4', 'C6', 'C1'],
 'NV5': ['C4', None, 'C6', 'C6', 'C6', 'C4'],
 'NV6': ['C6', None, 'C6', 'C6', None, 'C4'],
 'NV7': [None, None, None, None, None, 'C4'],
 'NV8': [None, None, None, None, None, 'C5'],
 'NV9': [None, None, None, None, None, 'C6'],
 'NV10': [None, None, None, None, None, 'C6']}

In [119]:
schedule_1 = task2.solve(schedule_1)
schedule_1

{'NV0': [None, None, 'C1', 'C1', None, 'C1'],
 'NV1': [None, 'C1', None, 'C1', None, 'C1'],
 'NV2': [None, 'C1', None, 'C1', None, 'C1'],
 'NV3': [None, 'C1', None, 'C3', None, 'C1'],
 'NV4': [None, 'C6', None, 'C4', None, 'C1'],
 'NV5': ['C1', None, None, 'C6', 'C1', 'C4'],
 'NV6': ['C1', None, 'C1', None, 'C1', 'C4'],
 'NV7': ['C1', None, 'C1', None, 'C3', 'C4'],
 'NV8': ['C1', None, 'C3', None, 'C4', 'C6'],
 'NV9': ['C4', None, 'C4', None, 'C6', 'C6'],
 'NV10': ['C4', None, 'C6', None, 'C6', 'C6'],
 'NV11': ['C6', None, 'C6', 'C6', None, 'C6']}

In [120]:
schedule_1 = task3.solve(shifts_dict, table_1, schedule_1)
schedule_1

        message: Optimization terminated successfully. (HiGHS Status 7: Optimal)
        success: True
         status: 0
            fun: 46.0
              x: [ 1.000e+00  0.000e+00 ...  0.000e+00  0.000e+00]
            nit: -1
          lower:  residual: [ 1.000e+00  0.000e+00 ...  0.000e+00
                              0.000e+00]
                 marginals: [ 0.000e+00  0.000e+00 ...  0.000e+00
                              0.000e+00]
          upper:  residual: [       inf        inf ...        inf
                                    inf]
                 marginals: [ 0.000e+00  0.000e+00 ...  0.000e+00
                              0.000e+00]
          eqlin:  residual: []
                 marginals: []
        ineqlin:  residual: [ 0.000e+00  1.000e+00 ...  0.000e+00
                              0.000e+00]
                 marginals: [ 0.000e+00  0.000e+00 ...  0.000e+00
                              0.000e+00]
 mip_node_count: 1
 mip_dual_bound: 46.0
        mip_gap: 0.0
[1.

{'NV0': ['C1', None, 'C6', 'C1', None, 'C4'],
 'NV1': ['C3', None, 'C1', 'C6', None, 'C1'],
 'NV2': [None, 'C6', 'C1', None, None, 'C1'],
 'NV3': ['C3', 'C1', None, None, None, 'C6'],
 'NV4': ['C6', None, None, 'C1', 'C3', 'C1'],
 'NV5': [None, 'C1', None, None, 'C6', 'C3'],
 'NV6': ['C1', None, None, 'C6', None, 'C1'],
 'NV7': [None, 'C6', None, None, 'C1', 'C1'],
 'NV8': ['C1', 'C1', 'C6', 'C3', None, 'C4'],
 'NV9': [None, 'C3', 'C4', 'C1', 'C1', 'C6'],
 'NV10': [None, 'C3', 'C1', 'C4', 'C6', 'C1'],
 'NV11': ['C6', None, 'C3', None, 'C4', 'C1']}

In [121]:
schedule_2 = task2.solve(schedule_2)
schedule_2

{'NV0': [None, 'C1', None, 'C1', None, 'C1'],
 'NV1': [None, 'C1', None, 'C1', None, 'C1'],
 'NV2': [None, 'C1', None, 'C1', 'C1', 'C1'],
 'NV3': [None, 'C6', None, 'C3', 'C1', 'C1'],
 'NV4': ['C1', None, 'C1', None, 'C3', 'C1'],
 'NV5': ['C1', None, 'C1', None, 'C4', 'C4'],
 'NV6': ['C1', None, 'C1', None, 'C6', 'C4'],
 'NV7': ['C1', None, 'C3', None, 'C6', 'C4'],
 'NV8': ['C4', None, 'C4', 'C4', None, 'C5'],
 'NV9': ['C4', None, 'C6', 'C6', None, 'C6'],
 'NV10': ['C6', None, 'C6', 'C6', None, 'C6']}

In [122]:
schedule_2 = task3.solve(shifts_dict, table_2, schedule_2)
schedule_2

        message: Optimization terminated successfully. (HiGHS Status 7: Optimal)
        success: True
         status: 0
            fun: 45.0
              x: [ 1.000e+00  0.000e+00 ...  0.000e+00  1.000e+00]
            nit: -1
          lower:  residual: [ 1.000e+00  0.000e+00 ...  0.000e+00
                              1.000e+00]
                 marginals: [ 0.000e+00  0.000e+00 ...  0.000e+00
                              0.000e+00]
          upper:  residual: [       inf        inf ...        inf
                                    inf]
                 marginals: [ 0.000e+00  0.000e+00 ...  0.000e+00
                              0.000e+00]
          eqlin:  residual: []
                 marginals: []
        ineqlin:  residual: [ 0.000e+00  0.000e+00 ...  1.000e+00
                              1.000e+00]
                 marginals: [ 0.000e+00  0.000e+00 ...  0.000e+00
                              0.000e+00]
 mip_node_count: 1
 mip_dual_bound: 45.0
        mip_gap: 0.0
[1.

{'NV0': ['C1', 'C1', None, 'C6', None, 'C3'],
 'NV1': ['C3', 'C6', None, 'C1', None, 'C5'],
 'NV2': ['C4', 'C5', 'C1', 'C1', None, 'C6'],
 'NV3': ['C6', None, 'C3', 'C1', None, 'C1'],
 'NV4': ['C1', 'C1', None, None, 'C6', 'C4'],
 'NV5': ['C1', None, 'C6', None, None, 'C1'],
 'NV6': [None, 'C3', 'C6', None, 'C1', 'C1'],
 'NV7': [None, 'C6', 'C4', 'C5', 'C1', 'C3'],
 'NV8': [None, 'C1', None, 'C6', 'C4', 'C1'],
 'NV9': [None, None, 'C1', None, 'C6', 'C1'],
 'NV10': ['C1', None, 'C1', 'C4', 'C3', 'C6']}

In [123]:
# add sunday col to schedule_1
schedule_1 = { employee: shift + [None] for employee, shift in schedule_1.items()}
schedule_1

{'NV0': ['C1', None, 'C6', 'C1', None, 'C4', None],
 'NV1': ['C3', None, 'C1', 'C6', None, 'C1', None],
 'NV2': [None, 'C6', 'C1', None, None, 'C1', None],
 'NV3': ['C3', 'C1', None, None, None, 'C6', None],
 'NV4': ['C6', None, None, 'C1', 'C3', 'C1', None],
 'NV5': [None, 'C1', None, None, 'C6', 'C3', None],
 'NV6': ['C1', None, None, 'C6', None, 'C1', None],
 'NV7': [None, 'C6', None, None, 'C1', 'C1', None],
 'NV8': ['C1', 'C1', 'C6', 'C3', None, 'C4', None],
 'NV9': [None, 'C3', 'C4', 'C1', 'C1', 'C6', None],
 'NV10': [None, 'C3', 'C1', 'C4', 'C6', 'C1', None],
 'NV11': ['C6', None, 'C3', None, 'C4', 'C1', None]}

In [124]:
# add saturday col to schedule_1
offset = len(schedule_2.keys())
for employee, shift in schedule_2.items():
    shift.insert(-1, None)
schedule_2 = {f"NV{int(employee[-1])+ offset}": shift for employee, shift in schedule_2.items()}
schedule_2

{'NV11': ['C1', None, 'C1', 'C4', 'C3', None, 'C6'],
 'NV12': ['C3', 'C6', None, 'C1', None, None, 'C5'],
 'NV13': ['C4', 'C5', 'C1', 'C1', None, None, 'C6'],
 'NV14': ['C6', None, 'C3', 'C1', None, None, 'C1'],
 'NV15': ['C1', 'C1', None, None, 'C6', None, 'C4'],
 'NV16': ['C1', None, 'C6', None, None, None, 'C1'],
 'NV17': [None, 'C3', 'C6', None, 'C1', None, 'C1'],
 'NV18': [None, 'C6', 'C4', 'C5', 'C1', None, 'C3'],
 'NV19': [None, 'C1', None, 'C6', 'C4', None, 'C1'],
 'NV20': [None, None, 'C1', None, 'C6', None, 'C1']}

In [125]:
merge = list(schedule_1.items()) + list(schedule_2.items())
merge = {employee: shift for employee, shift in merge}
merge

{'NV0': ['C1', None, 'C6', 'C1', None, 'C4', None],
 'NV1': ['C3', None, 'C1', 'C6', None, 'C1', None],
 'NV2': [None, 'C6', 'C1', None, None, 'C1', None],
 'NV3': ['C3', 'C1', None, None, None, 'C6', None],
 'NV4': ['C6', None, None, 'C1', 'C3', 'C1', None],
 'NV5': [None, 'C1', None, None, 'C6', 'C3', None],
 'NV6': ['C1', None, None, 'C6', None, 'C1', None],
 'NV7': [None, 'C6', None, None, 'C1', 'C1', None],
 'NV8': ['C1', 'C1', 'C6', 'C3', None, 'C4', None],
 'NV9': [None, 'C3', 'C4', 'C1', 'C1', 'C6', None],
 'NV10': [None, 'C3', 'C1', 'C4', 'C6', 'C1', None],
 'NV11': ['C1', None, 'C1', 'C4', 'C3', None, 'C6'],
 'NV12': ['C3', 'C6', None, 'C1', None, None, 'C5'],
 'NV13': ['C4', 'C5', 'C1', 'C1', None, None, 'C6'],
 'NV14': ['C6', None, 'C3', 'C1', None, None, 'C1'],
 'NV15': ['C1', 'C1', None, None, 'C6', None, 'C4'],
 'NV16': ['C1', None, 'C6', None, None, None, 'C1'],
 'NV17': [None, 'C3', 'C6', None, 'C1', None, 'C1'],
 'NV18': [None, 'C6', 'C4', 'C5', 'C1', None, 'C3'],
 'N

In [126]:
task3.solve(shifts_dict, day_dict, merge)

        message: Optimization terminated successfully. (HiGHS Status 7: Optimal)
        success: True
         status: 0
            fun: 83.0
              x: [ 0.000e+00  0.000e+00 ...  0.000e+00  0.000e+00]
            nit: -1
          lower:  residual: [ 0.000e+00  0.000e+00 ...  0.000e+00
                              0.000e+00]
                 marginals: [ 0.000e+00  0.000e+00 ...  0.000e+00
                              0.000e+00]
          upper:  residual: [       inf        inf ...        inf
                                    inf]
                 marginals: [ 0.000e+00  0.000e+00 ...  0.000e+00
                              0.000e+00]
          eqlin:  residual: []
                 marginals: []
        ineqlin:  residual: [ 1.000e+00  1.000e+00 ...  0.000e+00
                              0.000e+00]
                 marginals: [ 0.000e+00  0.000e+00 ...  0.000e+00
                              0.000e+00]
 mip_node_count: 1
 mip_dual_bound: 83.0
        mip_gap: 0.0
[ 0

{'NV0': [None, None, 'C6', 'C1', 'C1', None, 'C3'],
 'NV1': ['C1', 'C6', None, 'C1', 'C3', None, None],
 'NV2': ['C1', None, None, None, None, 'C6', None],
 'NV3': [None, 'C4', 'C1', 'C6', None, 'C1', 'C3'],
 'NV4': ['C1', 'C5', None, None, 'C3', 'C6', 'C1'],
 'NV5': [None, None, 'C1', None, 'C6', 'C1', None],
 'NV6': ['C1', None, None, 'C6', None, 'C1', None],
 'NV7': [None, 'C1', 'C1', 'C4', None, 'C6', None],
 'NV8': ['C4', 'C1', 'C1', None, None, 'C6', None],
 'NV9': [None, 'C1', 'C5', 'C3', 'C1', None, 'C6'],
 'NV10': ['C1', 'C1', 'C6', 'C3', None, None, 'C4'],
 'NV11': ['C6', None, 'C1', None, None, 'C1', 'C5'],
 'NV12': [None, None, None, None, 'C1', 'C6', 'C1'],
 'NV13': [None, 'C1', 'C3', 'C1', 'C6', None, None],
 'NV14': ['C1', None, 'C5', 'C1', None, None, 'C6'],
 'NV15': ['C3', 'C6', None, None, None, None, 'C1'],
 'NV16': [None, 'C1', 'C1', 'C6', None, 'C5', None],
 'NV17': ['C6', None, None, 'C1', 'C4', 'C3', 'C1'],
 'NV18': ['C1', 'C3', 'C6', None, None, None, None],
 'N

In [128]:
from solutions import task3_mod

new_shift_dict = shifts_dict.copy()
new_shift_dict['C0'] = [0] * len(list(shifts_dict.values())[0])

task3_mod.solve(shifts_dict, day_dict, merge)

        message: Optimization terminated successfully. (HiGHS Status 7: Optimal)
        success: True
         status: 0
            fun: 83.0
              x: [ 0.000e+00  0.000e+00 ... -0.000e+00  1.000e+00]
            nit: -1
          lower:  residual: [ 0.000e+00  0.000e+00 ... -0.000e+00
                              1.000e+00]
                 marginals: [ 0.000e+00  0.000e+00 ...  0.000e+00
                              0.000e+00]
          upper:  residual: [       inf        inf ...        inf
                                    inf]
                 marginals: [ 0.000e+00  0.000e+00 ...  0.000e+00
                              0.000e+00]
          eqlin:  residual: []
                 marginals: []
        ineqlin:  residual: [ 0.000e+00  0.000e+00 ...  0.000e+00
                              0.000e+00]
                 marginals: [ 0.000e+00  0.000e+00 ...  0.000e+00
                              0.000e+00]
 mip_node_count: 1
 mip_dual_bound: 83.0
        mip_gap: 0.0
[ 0

{'NV0': ['C6', 'C1', 'C4', 'C3', None, 'C1', None],
 'NV1': ['C1', 'C1', 'C4', 'C6', None, None, None],
 'NV2': [None, 'C1', None, 'C4', 'C6', 'C1', None],
 'NV3': [None, 'C5', 'C6', None, None, 'C1', 'C1'],
 'NV4': ['C1', None, None, None, None, 'C6', 'C1'],
 'NV5': ['C1', None, None, 'C5', None, 'C1', 'C6'],
 'NV6': ['C3', None, 'C1', 'C6', 'C1', None, None],
 'NV7': ['C1', None, 'C6', None, None, 'C1', None],
 'NV8': ['C1', 'C6', 'C1', None, None, None, None],
 'NV9': [None, None, 'C1', None, 'C6', 'C4', 'C1'],
 'NV10': ['C1', None, None, 'C6', 'C1', None, 'C3'],
 'NV11': ['C4', 'C6', 'C1', None, None, None, 'C1'],
 'NV12': [None, 'C6', None, 'C1', None, 'C1', None],
 'NV13': [None, 'C1', None, 'C1', 'C6', 'C3', None],
 'NV14': ['C6', None, None, 'C1', 'C4', 'C1', 'C5'],
 'NV15': ['C5', 'C1', 'C6', 'C4', 'C1', None, None],
 'NV16': [None, 'C5', None, None, 'C1', 'C6', None],
 'NV17': [None, 'C1', 'C1', 'C6', None, 'C3', 'C4'],
 'NV18': ['C6', None, None, 'C1', 'C3', None, 'C4'],
 'N